### ISSUE TITLE
Synthetic Recorder for Windows or Linux Machine[Enhancement] 

### ISSUE THREAD

**Issue by shahidrazam** [elastic/synthetics-recorder#120]
### Feature summary

Hey @vigneshshanmugam any recorder available with Windows or Linux machine. Mac one is working awesome.

Thanks and Best Regards,
Shahid Raza

**Comment by vigneshshanmugam** [comment]
@shahidrazam Thanks for testing our the Mac app and the feedback. 

Cross platform should not take huge work, its just that we have not spent time in testing those apps - https://github.com/elastic/synthetics-recorder/issues/118. Please watch out for the issue, will post here with more details once we figure out the release path for windows.

**Comment by rgundu10** [comment]
@vigneshshanmugam, can you please confirm when Synthetic Recorder is available for Windows machine?

**Comment by drewpost** [comment]
Just to update everyone on here. We currently have Windows and Linux builds prioritised for an upcoming release alongside a number of key usability enhancements.  Whilst I can't give exact dates, I can say to expect it sooner rather than later.

**Comment by rgundu10** [comment]
Please let me know if you have any updates on it.

**Comment by mholttech** [comment]
This is critical for us as my company does not allow developers to use a Mac

**Comment by mholttech** [comment]
It's not perfect but I was able to build a windows version using Ubuntu 20.04 and then copy in the Windows version of chromium. Replay functionality isn't working but at least we can record

**Comment by justinkambic** [comment]
An update here - we have done initial investigation getting this working with our release flow. At the moment, we successfully build/publish binaries for Windows and Linux, but they're missing the necessary Playwright Chromium browser to perform a recording session. Mac in this case is ok (because we're building on Macs).

The workaround is you can trigger these builds for their respective platforms and create a binary that will run on the system. 

We need to do some additional enhancement to our custom build scripts to ensure that the appropriate browsers are loaded for each bin that we build, instead of only loading the browser(s) required for the current platform.

This is on our current project board, so we will be actively working on it at some point in the near future.

**Comment by mholttech** [comment]
Thanks! This is also what I discovered when trying to build for Windows on Ubuntu. A simple sideload of the windows version of the Chromium browser into the correct path is what allowed me to provide my developers with a functional recorder. As I mentioned in my last post Replay functionality doesn't work but being able to record has given our engineers a better way to build synthetic tests.

**Comment by justinkambic** [comment]
I'm glad to hear you've gotten it working and it's useful for your team. Thanks for bearing with us while the recorder is still an alpha product!

**Comment by kyungeunni** [comment]
Hi all 👋 

Synthetics Recorder for Windows and Linux(debian) is available as of [0.0.1-alpha.3](https://github.com/elastic/synthetics-recorder/releases/tag/v0.0.1-alpha.3)
