### ISSUE TITLE
Improve new window experience on macOS

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#14]
After closing the window, on macOS the app continues to run. This is to be expected, as it's the standard convention for mac apps. However, there's not a good experience once the window is closed.

We should make it easy to open a fresh window when all windows have exited.

**Comment by kyungeunni** [comment]
This menu item is a bit confusing. When I saw this menu item, I thought the recorder is supposed to support multiple windows(which we don't). Also, I'm not sure if this menu item is ever going to be used because this feature would work only when the opened window is 0, but you need to have the window open already to click this menu.. 😅 I'm not sure if it's possible to just define the shortcut and drop this from the menu items.
