### ISSUE TITLE
[Enhancement] Convert Electron backend to TypeScript

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#141]
### Feature summary

When I contribute code to the backend processes for the recorder, I want to use TypeScript.

### Why is this feature important?

As we are starting to introduce more contributors to this project, it will be less prone for us to introduce bugs and regressions if we are using TS on the backend.

**Comment by vigneshshanmugam** [comment]
This might be more pain and cumbersome DX than bringing the benefits of using TS, we can be fine with JSDOC annotations if we want to stay away from bugs.

**Comment by lucasfcosta** [comment]
I think indeed it may cause some pain given we'd have to have something configure to rebuild the changed TS files every time they're changed rather than simply relying on the bundler as we do for the actual application within. I think this could be made simple though.

Besides that, I couldn't think of other reasons it could hurt DX. @vigneshshanmugam what else do you think could be a problem?

I'm not strongly opinionated here, but I'd personally prefer to have TS there.

**Comment by vigneshshanmugam** [comment]
I was thinking about the DX implications of running ts-node watch as it would be quite slow once we start adding in more things down the line. 

In any case, I dont have a strong opposition towards it. I will leave it up to you all.

**Comment by justinkambic** [comment]
Skipping Post-FF testing. This was largely a chore; given the other testing we will do it should cover the novel changes from this ticket.
