### ISSUE TITLE
Cannot open app on Mac[Bug] 

### ISSUE THREAD

**Issue by rbrunan** [elastic/synthetics-recorder#291]
### Bug summary

I downloaded the latest release of the app ([beta6 for mac](https://github.com/elastic/synthetics-recorder/releases/download/v0.0.1-beta.6/synthetics-recorder-0.0.1-beta.6-mac-arm64.dmg)) and I'm unable to run it on my MacOS Monterey v12.5.1. I have this error:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/48295668/186891569-374c2717-fa29-47cc-aa07-979f576e335c.png">
My mac release:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/48295668/186891620-50ea8091-c09b-4821-8480-1e33dfa0d2f5.png">

### Recorder Version

v0.0.1-beta.6

### Steps to reproduce

1. Download the app from https://github.com/elastic/synthetics-recorder/compare/v0.0.1-beta.4...v0.0.1-beta.6
2. Install it
3. Try to run it and receive:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/48295668/186891569-374c2717-fa29-47cc-aa07-979f576e335c.png">

### Expected behavior

Be able to run the app properly

**Comment by kyungeunni** [comment]
Sorry for the inconvenience, this is happening because the Mac app isn't notarized yet. We have prioritised this work and the update can be tracked in this issue: https://github.com/elastic/synthetics-recorder/issues/51

Meanwhile, you can bypass the warning message by following this [workaround](https://support.apple.com/en-gb/guide/mac-help/mh40616/mac), or clone the repository and run it locally (`nvm use && npm ci && npm run dev`).
